In [37]:
import numpy as np
from sklearn.neighbors import KDTree

In [30]:
a = np.random.rand(10000000,)

In [31]:
rev_a = np.sort(a)[::-1]

In [32]:
sort_ind = np.argsort(a)[::-1]

In [49]:
a[sort_ind[:10000]] == rev_a[:10000]

array([ True,  True,  True, ...,  True,  True,  True])

In [46]:
rev_a

array([9.99999996e-01, 9.99999847e-01, 9.99999826e-01, ...,
       2.32752528e-07, 1.58988612e-07, 1.03247095e-07])

In [10]:
from utils.ply import read_ply, write_ply
import numpy as np

In [28]:
cloud = read_ply('./pgscam_results/KPConv_NPM3d_7_cloud.ply')

hm = cloud['pgscam']

hm_clean = np.nan_to_num(hm, nan=0.0)

x = cloud['x']
y = cloud['y']
z = cloud['z']
preds = cloud['preds']
cls = cloud['class']
pgscam = hm_clean

write_ply('./pgscam_results/KPConv_NPM3d_7_act_22.ply', [x, y, z, preds, cls, pgscam], ['x', 'y', 'z', 'preds', 'class', 'pgscam'])

True

In [35]:
points = np.vstack((cloud['x'], cloud['y'], cloud['z'])).T

In [38]:
tree = KDTree(points, leaf_size=40)

In [43]:
x = np.random.rand(8000, 3)

In [51]:
tree = KDTree(x, leaf_size=40)

In [55]:
idx = tree.query(points, k=1, return_distance=False)

In [56]:
idx = idx.squeeze()

In [62]:
idx.shape

(8880908,)

In [58]:
proj = np.random.rand(8000,)

In [61]:
proj[idx].shape

(8880908,)

In [63]:
np.arange(0, 22)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])